package model

var SimpleNameToSQL = map[string]string{
	"string":             "VARCHAR(255)",
	"fixed string":       "CHAR(10)",
	"text":               "TEXT",
	"small text":         "TINYTEXT",
	"medium text":        "MEDIUMTEXT",
	"long text":          "LONGTEXT",
	"int":                "INT",
	"small int":          "SMALLINT",
	"tiny int":           "TINYINT",
	"big int":            "BIGINT",
	"medium int":         "MEDIUMINT",
	"decimal":            "DECIMAL(10,2)",
	"float":              "FLOAT",
	"real number":        "REAL",
	"double":             "DOUBLE",
	"boolean":            "BOOLEAN",
	"date":               "DATE",
	"time":               "TIME",
	"datetime":           "DATETIME",
	"timestamp":          "TIMESTAMP",
	"year":               "YEAR",
	"fixed binary":       "BINARY(16)",
	"binary":             "VARBINARY(255)",
	"small binary blob":  "TINYBLOB",
	"binary blob":        "BLOB",
	"medium binary blob": "MEDIUMBLOB",
	"large binary blob":  "LONGBLOB",
	"json":               "JSON",
	"enum":               "ENUM('a','b')", // example placeholder
	"set":                "SET('a','b')",  // example placeholder
	"uuid":               "CHAR(36)",
	"xml":                "XML",
	"geometry":           "GEOMETRY",
	"point":              "POINT",
	"line":               "LINESTRING",
	"polygon":            "POLYGON",
	"bit":                "BIT(1)",
	"interval":           "INTERVAL",
	"currency":           "MONEY",
	"auto-increment int": "SERIAL",
}
